subscription_id              = "8137c2f4-3363-4a3b-93f6-c6acd62fbd52"
resource_group_name          = "manageddemorglatest"
location                     = "East US"
vnet_name                    = "managed-demo-vnet-terralatest"
vnet_address_space           = ["10.0.0.0/18"]
subnet_bastion_name          = "bastion-sub"
subnet_bastion_address_prefix= "10.0.0.0/24"
storage_account_name         = "managedsa2demo"
storage_container_names      = ["manageddemocontainer", "manageddemosastoragecont", "manageddemosastoragecontainer"]
